"""initial migration

Revision ID: 2d1a801a0bb3
Revises: 
Create Date: 2025-12-10 19:38:26.190560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2d1a801a0bb3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('jobs', 'status',
               existing_type=postgresql.ENUM('open', 'closed', name='jobstatus'),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('jobs', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('jobs', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('open', 'closed', name='jobstatus'),
               existing_nullable=True)
    op.alter_column('jobs', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
